# Generated by Django 5.0.2 on 2025-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session_jti',
            field=models.CharField(blank=True, help_text='Tracks the JWT ID of the currently active session', max_length=255, null=True),
        ),
    ]
