# Generated by Django 5.1.14 on 2025-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='client',
            field=models.CharField(max_length=255),
        ),
    ]
