# Generated by Django 5.0.2 on 2025-12-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='accounts_us_user_id_9dddef_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='accounts_us_jti_3b448e_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='jti',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'role', 'is_active'], name='accounts_us_user_id_68939c_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_superuser', True)), fields=('phone',), name='unique_superuser_phone'),
        ),
    ]
