# Generated by Django 5.0.2 on 2025-12-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_usersession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneotp',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='phoneotp',
            name='accounts_ph_phone_65eb93_idx',
        ),
    ]
