# Generated by Django 5.0.2 on 2025-12-21 19:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('capacity', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Unique Warehouse Code (e.g. BLR-01)', max_length=50, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('service_radius_km', models.FloatField(default=3.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BinInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('reserved_qty', models.PositiveIntegerField(default=0)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='warehouse.bin')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sku')),
            ],
        ),
        migrations.CreateModel(
            name='CycleCountTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_tasks', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_tasks', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='CycleCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.IntegerField()),
                ('counted_qty', models.IntegerField(blank=True, null=True)),
                ('adjusted', models.BooleanField(default=False)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.bin')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sku')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.cyclecounttask')),
            ],
        ),
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('putaway_complete', 'Putaway Complete')], db_index=True, default='pending', max_length=30)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.IntegerField()),
                ('received_qty', models.IntegerField(default=0)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.grn')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sku')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('route', models.CharField(help_text="Where this key came from (e.g. 'razorpay_webhook')", max_length=100)),
                ('response_status', models.IntegerField(default=200)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'route'], name='warehouse_i_key_1ee1d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PickingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('picker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_tasks', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PackingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PACKING', 'Packing'), ('PACKED', 'Packed')], db_index=True, default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_tasks', to=settings.AUTH_USER_MODEL)),
                ('picking_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packing_task', to='warehouse.pickingtask')),
            ],
        ),
        migrations.CreateModel(
            name='PickItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_to_pick', models.PositiveIntegerField()),
                ('picked_qty', models.PositiveIntegerField(default=0)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.bin')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sku')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.pickingtask')),
            ],
        ),
        migrations.CreateModel(
            name='FulfillmentCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('refund_initiated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pick_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fc_records', to='warehouse.pickitem')),
            ],
        ),
        migrations.CreateModel(
            name='PickSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('reopen_after_scan', models.BooleanField(default=False, help_text='If true, picker can try to re-scan after resolution.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pick_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='warehouse.pickitem')),
                ('skipped_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='warehouse.pickingtask')),
            ],
        ),
        migrations.CreateModel(
            name='PutawayTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_task', to='warehouse.grn')),
                ('putaway_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_tasks', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PutawayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_qty', models.IntegerField(default=0)),
                ('grn_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.grnitem')),
                ('placed_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.bin')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.putawaytask')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='warehouse.aisle')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='warehouse.shelf'),
        ),
        migrations.CreateModel(
            name='ShortPickIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_picked_qty', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('skip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse.pickskip')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_change', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('INWARD', 'Inward (GRN)'), ('OUTWARD', 'Outward (Dispatch)'), ('ADJUSTMENT', 'Adjustment (Lost/Found)'), ('RESERVE', 'Order Reservation'), ('PUTAWAY', 'Putaway'), ('ROLLBACK', 'Rollback'), ('CYCLE_COUNT', 'Cycle Count')], max_length=32)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.bin')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'North Zone', 'Downtown Area'", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Service area boundary', null=True, srid=4326)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Center of service area', null=True, srid=4326)),
                ('radius_km', models.FloatField(default=5.0, help_text='Radius in kilometers if using point-based coverage')),
                ('delivery_time_minutes', models.IntegerField(default=30, help_text='Estimated delivery time in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
            },
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=128)),
                ('pickup_otp', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('assigned', 'Rider Assigned'), ('handed_over', 'Handed Over to Rider')], db_index=True, default='ready', max_length=30)),
                ('rider_id', models.CharField(blank=True, db_index=True, help_text='ID of rider assigned by delivery service', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packing_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_record', to='warehouse.packingtask')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehouse.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bins_direct', to='warehouse.zone'),
        ),
        migrations.AddField(
            model_name='aisle',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='warehouse.zone'),
        ),
        migrations.AddConstraint(
            model_name='bininventory',
            constraint=models.CheckConstraint(check=models.Q(('qty__gte', 0)), name='bin_inventory_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='bininventory',
            constraint=models.CheckConstraint(check=models.Q(('reserved_qty__lte', models.F('qty'))), name='bin_inventory_reserved_lte_qty'),
        ),
        migrations.AlterUniqueTogether(
            name='bininventory',
            unique_together={('bin', 'sku')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['sku', 'warehouse'], name='warehouse_s_sku_id_0f06d4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'timestamp'], name='warehouse_s_movemen_f88d71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('warehouse', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='bin',
            unique_together={('shelf', 'bin_code')},
        ),
    ]
