# Generated by Django 5.0.2 on 2025-11-30 20:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='lng',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddConstraint(
            model_name='bininventory',
            constraint=models.CheckConstraint(check=models.Q(('qty__gte', 0)), name='bin_inventory_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='bininventory',
            constraint=models.CheckConstraint(check=models.Q(('reserved_qty__gte', 0)), name='bin_inventory_reserved_qty_gte_0'),
        ),
    ]
