# Generated by Django 5.0.2 on 2025-12-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_warehouse_lat_remove_warehouse_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrecord',
            name='rider_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pickskip',
            name='reopen_after_scan',
            field=models.BooleanField(default=False),
        ),
    ]
