# Generated by Django 5.0.2 on 2025-12-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_dispatchrecord_rider_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrecord',
            name='rider_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID of rider assigned by delivery service', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pickskip',
            name='reopen_after_scan',
            field=models.BooleanField(default=False, help_text='If true, picker can try to re-scan after resolution.'),
        ),
    ]
