# Generated by Django 5.0.2 on 2025-12-09 09:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_dispatchrecord_rider_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'North Zone', 'Downtown Area'", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Service area boundary', null=True, srid=4326)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Center of service area', null=True, srid=4326)),
                ('radius_km', models.FloatField(default=5.0, help_text='Radius in kilometers if using point-based coverage')),
                ('delivery_time_minutes', models.IntegerField(default=30, help_text='Estimated delivery time in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
            },
        ),
    ]
