# Generated by Django 5.0.2 on 2025-12-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_servicearea'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bininventory',
            name='bin_inventory_qty_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='bininventory',
            name='bin_inventory_reserved_qty_gte_0',
        ),
    ]
