# Generated by Django 5.0.2 on 2025-12-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_install_trigram'),
        ('warehouse', '0006_remove_bininventory_bin_inventory_qty_gte_0_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bininventory',
            constraint=models.CheckConstraint(check=models.Q(('qty__gte', 0)), name='bin_inventory_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='bininventory',
            constraint=models.CheckConstraint(check=models.Q(('reserved_qty__lte', models.F('qty'))), name='bin_inventory_reserved_lte_qty'),
        ),
    ]
