# apps/orders/urls.py
from rest_framework import routers
from django.urls import path
from .views import CheckoutView, OrderViewSet, CartView, AddToCartView, PaymentVerificationView

# Remove CancelOrderView from imports because it doesn't exist as a standalone view

router = routers.DefaultRouter()
router.register(r'', OrderViewSet, basename='orders')

urlpatterns = router.urls + [
    # Checkout & payment
    path('create/', CheckoutView.as_view(), name='create-order'),
    path('payment/verify/', PaymentVerificationView.as_view(), name='payment-verify'),

    # Cart endpoints
    path('cart/', CartView.as_view(), name='cart-detail'),
    path('cart/add/', AddToCartView.as_view(), name='cart-add'),

    # Note: The 'cancel' endpoint is automatically generated by the router 
    # because it is defined as an @action in OrderViewSet.
    # URL: /api/v1/orders/<pk>/cancel/
]