# Generated by Django 5.0.2 on 2025-12-21 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('available_qty', models.IntegerField(default=0)),
                ('reserved_qty', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='catalog.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Inventory Stock',
                'verbose_name_plural': 'Inventory Stocks',
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delta_available', models.IntegerField(default=0)),
                ('delta_reserved', models.IntegerField(default=0)),
                ('available_after', models.IntegerField()),
                ('reserved_after', models.IntegerField()),
                ('change_type', models.CharField(blank=True, max_length=64)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_history', to='catalog.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_history', to='warehouse.warehouse')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventorystock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['warehouse', 'sku'], name='inventory_i_warehou_c4b9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['sku'], name='inventory_i_sku_id_3da944_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(check=models.Q(('available_qty__gte', 0)), name='inventory_stock_available_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(check=models.Q(('reserved_qty__gte', 0)), name='inventory_stock_reserved_qty_gte_0'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorystock',
            unique_together={('warehouse', 'sku')},
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['warehouse', 'sku', 'created_at'], name='inventory_i_warehou_c53ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['change_type', 'created_at'], name='inventory_i_change__d60ebf_idx'),
        ),
    ]
