# Generated by Django 5.0.2 on 2025-11-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventorystock',
            name='inventory_i_availab_960ceb_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorystock',
            name='inventory_i_updated_cb053e_idx',
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(check=models.Q(('available_qty__gte', 0)), name='inventory_stock_available_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(check=models.Q(('reserved_qty__gte', 0)), name='inventory_stock_reserved_qty_gte_0'),
        ),
    ]
