# Generated by Django 5.0.2 on 2025-12-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventorystock_inventory_i_availab_960ceb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='change_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
