# Generated by Django 5.2.8 on 2025-11-24 07:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_paid_orders', models.PositiveIntegerField(default=0)),
                ('total_cancelled_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'verbose_name': 'Daily Sales Summary',
                'verbose_name_plural': 'Daily Sales Summaries',
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshotDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closing_available_qty', models.IntegerField(default=0)),
                ('closing_reserved_qty', models.IntegerField(default=0)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='catalog.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Inventory Daily Snapshot',
                'verbose_name_plural': 'Inventory Daily Snapshots',
                'unique_together': {('date', 'warehouse', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='RiderKPISnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tasks_assigned', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('tasks_failed', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('avg_delivery_time_seconds', models.PositiveIntegerField(default=0)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='accounts.riderprofile')),
            ],
            options={
                'verbose_name': 'Rider KPI Snapshot',
                'verbose_name_plural': 'Rider KPI Snapshots',
                'unique_together': {('date', 'rider')},
            },
        ),
        migrations.CreateModel(
            name='SKUAnalyticsDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('avg_selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('refunds_count', models.PositiveIntegerField(default=0)),
                ('refunded_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='catalog.sku')),
            ],
            options={
                'verbose_name': 'SKU Daily Analytics',
                'verbose_name_plural': 'SKU Daily Analytics',
                'unique_together': {('date', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseKPISnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orders_created', models.PositiveIntegerField(default=0)),
                ('orders_dispatched', models.PositiveIntegerField(default=0)),
                ('orders_delivered', models.PositiveIntegerField(default=0)),
                ('orders_cancelled', models.PositiveIntegerField(default=0)),
                ('avg_pick_time_seconds', models.PositiveIntegerField(default=0)),
                ('avg_pack_time_seconds', models.PositiveIntegerField(default=0)),
                ('avg_dispatch_to_delivery_seconds', models.PositiveIntegerField(default=0)),
                ('short_pick_incidents', models.PositiveIntegerField(default=0)),
                ('full_cancellations', models.PositiveIntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse KPI Snapshot',
                'verbose_name_plural': 'Warehouse KPI Snapshots',
                'unique_together': {('date', 'warehouse')},
            },
        ),
    ]
