# Generated by Django 5.0.2 on 2025-12-21 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField(help_text='External URL or Cloudinary link')),
                ('target_url', models.CharField(help_text='/category.html?slug=veg or /product.html?code=...', max_length=255)),
                ('position', models.CharField(choices=[('HERO', 'Hero Slider'), ('MID', 'Middle Banner')], default='HERO', max_length=10)),
                ('bg_gradient', models.CharField(default='linear-gradient(135deg, #32CD32 0%, #2ecc71 100%)', help_text='CSS Gradient string', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='catalog_bra_slug_65677f_idx'), models.Index(fields=['is_active'], name='catalog_bra_is_acti_0ff477_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_code', models.CharField(db_index=True, help_text='Human-readable code (e.g. MILK-1L-AMUL)', max_length=100, unique=True)),
                ('primary_barcode', models.CharField(blank=True, help_text='EAN/UPC or primary barcode (optional)', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='pcs', help_text='Unit like pcs, kg, g, ltr, ml, pack', max_length=50)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Customer-facing selling price', max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Internal purchase cost price', max_digits=10)),
                ('max_order_qty', models.PositiveIntegerField(default=20, help_text='Max quantity allowed per order')),
                ('min_order_qty', models.PositiveIntegerField(default=1, help_text='Minimum quantity per order')),
                ('hsn_code', models.CharField(blank=True, max_length=32)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='GST percentage (e.g. 5.00 for 5%)', max_digits=5)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_returnable', models.BooleanField(default=True)),
                ('weight_grams', models.PositiveIntegerField(blank=True, help_text='Weight in grams (for logistics)', null=True)),
                ('volume_ml', models.PositiveIntegerField(blank=True, help_text='Volume in ml (if applicable)', null=True)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, help_text='Shelf life in days (optional)', null=True)),
                ('search_keywords', models.TextField(blank=True, help_text='Space/comma separated extra search keywords')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra attributes like pack_type, flavor, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus', to='catalog.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_quantity', models.PositiveIntegerField(default=100)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.sku')),
            ],
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_695af4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'sort_order'], name='catalog_cat_parent__57266d_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='catalog_cat_is_acti_7db955_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_category_per_parent_name'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['is_active', 'category'], name='catalog_sku_is_acti_a855bb_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['is_active', 'brand'], name='catalog_sku_is_acti_e9adbb_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['sale_price'], name='catalog_sku_sale_pr_8a685c_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['created_at'], name='catalog_sku_created_9e41a0_idx'),
        ),
    ]
