# Generated by Django 5.0.2 on 2025-12-04 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField(help_text='External URL or Cloudinary link')),
                ('target_url', models.CharField(help_text='/category.html?slug=veg or /product.html?code=...', max_length=255)),
                ('position', models.CharField(choices=[('HERO', 'Hero Slider'), ('MID', 'Middle Banner')], default='HERO', max_length=10)),
                ('bg_gradient', models.CharField(default='linear-gradient(135deg, #32CD32 0%, #2ecc71 100%)', help_text='CSS Gradient string', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_quantity', models.PositiveIntegerField(default=100)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.sku')),
            ],
        ),
    ]
