# Generated by Django 5.0.2 on 2025-12-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_install_trigram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bg_gradient',
            field=models.CharField(default='linear-gradient(135deg, #32CD32 0%, #2ecc71 100%)', help_text='CSS Gradient string', max_length=255),
        ),
    ]
